# Generated by Django 4.0.2 on 2022-03-18 17:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('contact_data', models.CharField(max_length=128)),
                ('car', models.CharField(max_length=128)),
                ('seats', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rooms', models.IntegerField(default=1)),
                ('kitchen', models.IntegerField(default=1)),
                ('bath', models.IntegerField(default=1)),
                ('owner_first_name', models.CharField(max_length=1024)),
                ('owner_last_name', models.CharField(max_length=1024)),
                ('max_male', models.IntegerField(default=0)),
                ('max_kids', models.IntegerField(default=0)),
                ('max_adults', models.IntegerField(default=0)),
                ('min_age', models.IntegerField(default=0)),
                ('max_kids_age', models.IntegerField(default=18)),
            ],
            options={
                'ordering': ['rooms'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=1024)),
                ('wish_city', models.CharField(max_length=1024)),
                ('group_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugeerouter.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('contact', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_location', models.CharField(max_length=1024)),
                ('end_location', models.CharField(max_length=1024)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugeerouter.driver')),
                ('end_flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refugeerouter.flat')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugeerouter.group')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Refugee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=1024)),
                ('last_name', models.CharField(max_length=1024)),
                ('age', models.IntegerField(default=1)),
                ('gender', models.IntegerField(default=1)),
                ('contact_data', models.CharField(max_length=1024)),
                ('origin', models.CharField(max_length=1024)),
                ('origin_checked', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugeerouter.group')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugeerouter.flat')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugeerouter.group')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
