# Generated by Django 4.0.2 on 2022-03-18 14:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rooms', models.IntegerField(default=1)),
                ('kitchen', models.IntegerField(default=1)),
                ('bath', models.IntegerField(default=1)),
                ('max_kids', models.IntegerField(default=0)),
                ('max_adults', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('contact', models.CharField(max_length=128)),
                ('car', models.CharField(max_length=128)),
                ('seats', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Notifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('contact', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=128)),
                ('num_kids', models.IntegerField(default=0)),
                ('num_adults', models.IntegerField(default=0)),
                ('names', models.CharField(max_length=1024)),
                ('wish_city', models.CharField(max_length=1024)),
                ('group_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugeerouter.group')),
            ],
        ),
    ]
