# Generated by Django 4.0.2 on 2022-03-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refugeerouter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugee',
            name='age',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('D', 'Diverse')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refugeerouter.group'),
        ),
    ]
