# Generated by Django 4.0.2 on 2022-03-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugeerouter', '0002_alter_refugee_age_alter_refugee_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='min_age',
            new_name='min_kids_age',
        ),
        migrations.AddField(
            model_name='flat',
            name='address',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='contact_data',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='shared_bath',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='shared_kitchen',
            field=models.BooleanField(default=True),
        ),
    ]
