# Generated by Django 4.0.2 on 2022-03-19 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refugeerouter', '0003_rename_min_age_flat_min_kids_age_flat_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refugeerouter.group'),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='gender',
            field=models.CharField(choices=[('D', 'Diverse'), ('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], default='U', max_length=1),
        ),
    ]
