# Generated by Django 4.0.2 on 2022-03-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refugeerouter', '0004_alter_group_group_relation_alter_refugee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugee',
            name='contact_data',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='first_name',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refugees', to='refugeerouter.group'),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='last_name',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='origin',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
