# Generated by Django 4.0.2 on 2022-03-20 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refugeerouter', '0005_alter_refugee_contact_data_alter_refugee_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='interim',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refugeerouter.group'),
        ),
    ]
