# Generated by Django 4.0.2 on 2022-03-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refugeerouter', '0007_alter_driver_options_alter_flat_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifier',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end_flat',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='group',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
