# Generated by Django 4.0.2 on 2022-03-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugeerouter', '0009_booking_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='flat',
            name='notes',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='group',
            name='notes',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='notes',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
